name: ­ЮЎЙ­ЮџЂ­ЮЎ╝­ЮЎ░­ЮЎй-­ЮџЄ­ЮЎ╝­ЮЎ│ рхЄрхњрхЌ
services:
  - name: ­ЮЎЙ­ЮџЂ­ЮЎ╝­ЮЎ░­ЮЎй-­ЮџЄ­ЮЎ╝­ЮЎ│-­Юџѓ­ЮЎ┤­ЮџЂ­ЮџЁ­ЮЎИ­ЮЎ▓­ЮЎ┤
    type: web
    ports:
      - 5000
    routes:
      - path: "/"
    build:
      type: docker
      dockerfile: ./Dockerfile
    regions:
      - fra
      - sin
      
